export const unsortedArray = [
  "dollars",
  "euros",
  "pounds",
  "yen",
  "rupees",
  "cents",
  "financial",
  "wealth",
  "investment",
  "banking",
  "savings",
  "budget",
  "stocks",
  "bonds",
  "interest",
  "dividends",
  "portfolio",
  "inflation",
  "deflation",
  "capital",
  "assets",
  "liabilities",
  "equity",
  "credit",
  "debit",
  "profits",
  "losses",
  "income",
  "expenses",
  "revenue",
  "taxes",
  "mortgage",
  "insurance",
  "retirement",
  "inheritance",
  "fortune",
  "cash",
  "check",
  "transaction",
  "loan",
  "debt",
  "funding",
  "venture",
  "acquisition",
  "merger",
  "wealthy",
  "affluent",
  "millionaire",
  "billionaire",
  "corporate",
  "finance",
  "financial",
  "economy",
  "market",
  "trading",
  "exchange",
  "bull",
  "bear",
  "portfolio",
  "yield",
  "diversification",
  "asset",
  "liability",
  "equity",
  "capital",
  "credit",
  "debit",
  "interest",
  "profit",
  "loss",
  "income",
  "expense",
  "revenue",
  "tax",
  "mortgage",
  "insurance",
  "retirement",
  "inheritance",
  "fortune",
  "currency",
  "coin",
  "bill",
  "note",
  "wallet",
  "purse",
  "bank",
  "ATM",
  "credit card",
  "debit card",
  "payment",
  "transaction",
  "loan",
  "debt",
  "fund",
  "venture",
  "acquisition",
  "merger",
  "wealthy",
  "affluent",
  "millionaire",
  "billionaire",
  "corporate",
  "business",
  "economics",
  "stock",
  "bond",
  "interest rate",
  "investment",
  "risk",
  "return",
  "dividend",
  "strategy",
  "analysis",
  "capital",
  "market",
  "trading",
  "exchange",
  "broker",
  "investment banking",
  "hedge fund",
  "private equity",
  "stock market",
  "bull market",
  "bear market",
  "portfolio management",
  "financial planning",
  "asset management",
  "retirement planning",
  "insurance policy",
  "economic growth",
  "market volatility",
  "recession",
  "inflation",
  "deflation",
  "financial statement",
  "cash flow",
  "budgeting",
  "tax planning",
  "credit score",
  "mortgage rate",
  "real estate",
  "commodities",
  "derivatives",
  "financial literacy",
  "money management",
  "entrepreneurship",
  "passive income",
  "financial independence",
  "wealth accumulation",
  "financial freedom",
  "frugal living",
  "side hustle",
  "stock portfolio",
  "investment portfolio",
  "diversified portfolio",
  "retirement savings",
  "compound interest",
  "wealth creation",
  "wealth management",
  "financial advisor",
  "financial education",
  "financial goals",
  "financial success",
  "financial mindset",
  "financial discipline",
  "financial stability",
  "financial security",
  "financial planning",
  "financial responsibility",
  "financial legacy",
  "financial legacy",
  "financial empowerment",
  "fruit",
  "apple",
  "banana",
  "orange",
  "grapefruit",
  "lemon",
  "lime",
  "strawberry",
  "blueberry",
  "raspberry",
  "blackberry",
  "cherry",
  "watermelon",
  "melon",
  "pineapple",
  "pear",
  "peach",
  "plum",
  "apricot",
  "kiwi",
  "mango",
  "papaya",
  "coconut",
  "avocado",
  "fig",
  "guava",
  "dragonfruit",
  "passionfruit",
  "persimmon",
  "lychee",
  "pomegranate",
  "cranberry",
  "gooseberry",
  "car brand",
  "Toyota",
  "money",
  "finance",
  "currency",
  "wealth",
  "investment",
  "savings",
  "budget",
  "apple",
  "banana",
  "orange",
  "grapefruit",
  "strawberry",
  "watermelon",
  "mango",
  "Toyota",
  "Ford",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Honda",
  "Tesla",
  "rich",
  "affluent",
  "prosperity",
  "luxury",
  "abundance",
  "opulence",
  "success",
];
